[package]
name = "example-opfs"
edition.workspace = true
license.workspace = true
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

# [features]
# default = ["fusio/aws", "fusio/opfs"]


[dependencies]
fusio = { path = "../../fusio", features = ["opfs"] }
fusio-dispatch = { path = "../../fusio-dispatch", features = ["opfs"] }
wasm-bindgen = "0.2.95"
wasm-bindgen-futures = { version = "0.4.45" }


[dev-dependencies]
wasm-bindgen-test = "0.3.34"
