[package]
description = "Parquet reader and writer implementations for Fusio."
edition.workspace = true
license.workspace = true
name = "fusio-parquet"
repository.workspace = true
version = "0.2.1"

[dependencies]
bytes = { workspace = true }
fusio = { version = "0.3.0", path = "../fusio", features = ["bytes", "dyn"] }
futures = { version = "0.3" }
parquet = { version = "53", features = ["arrow", "async"] }

[dev-dependencies]
arrow = "53"
rand = "0.8"
tempfile = "3.12.0"
